name: Move new issues into Project Boards
on:
  issues:
    types: [ opened ]
jobs:
  move-issue-to-repository-project-column:
    name: Move issues to repository project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'To do' column if body has a mark 'issue:todo'
        uses: fojia/action-move-issues-to-column@v1.0.0
        with:
          project: 'Actions Project'
          column: 'To do'
          issue: ${{ toJson(github.event.issue) }}
          owner: 'fojia'
          repo: 'action-move-issues-to-column'
          type: 'repo'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          marker: 'issue:todo'
      - name: Move issue to 'In Progress' column if body has a mark 'issue:inprogress'
        uses: fojia/action-move-issues-to-column@v1.0.0
        with:
          project: 'Actions Project'
          column: 'In progress'
          issue: ${{ toJson(github.event.issue) }}
          owner: 'fojia'
          repo: 'action-move-issues-to-column'
          type: 'repo'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          marker: 'issue:inprogress'